

services:
  backend:
    build: ./BackendDjango
    container_name: BackendDjango
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    volumes:
      - ./BackendDjango:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./web-builder2
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    command: npm run dev
    volumes:
      - ./web-builder2:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
