version: "3.9"

services:
  backend:
    build:
      context: ./BackendDjango
      dockerfile: Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./BackendDjango:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: ./web-builder2/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  postgres_data:
