# Generated by Django 5.2.3 on 2025-07-02 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_userprojectsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousProjectSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('current_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.project')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProjectSetting',
        ),
    ]
