# Generated by Django 5.2.4 on 2025-07-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_anonymousprojectsetting_delete_userprojectsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.JSONField(default=dict)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian lên lịch'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('scheduled', 'Đã lên lịch'), ('archived', 'Đã lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Thẻ (Tags)'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ảnh đại diện'),
        ),
    ]
